name: hermex

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: 3000
      NODE_ENV: ${NODE_ENV:-production}
      API_GATEWAY_URL: ${API_GATEWAY_URL:-http://api-gateway:4000}
      NEXT_PUBLIC_PAYMENT_PORTAL_URL: ${NEXT_PUBLIC_PAYMENT_PORTAL_URL:-http://localhost:3001}
    networks:
      - hermex-network

networks:
  hermex-network:
    name: hermex-network
    external: true
